name: Auto Tagging

on:
  push:
    branches:
      - production # Trigger on pushes to the production branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Explicitly grant write permission to contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read Version from package.json
        id: version
        run: |
          # Extract the current version from package.json
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current version from package.json: $CURRENT_VERSION"

          # Verify if the tag already exists
          if git rev-parse "v$CURRENT_VERSION" >/dev/null 2>&1; then
            echo "Tag v$CURRENT_VERSION already exists."
            echo "::set-output name=TAG_EXISTS::true"
          else
            echo "Tag v$CURRENT_VERSION does not exist."
            echo "::set-output name=NEXT_VERSION::v$CURRENT_VERSION"
            echo "::set-output name=TAG_EXISTS::false"
          fi

      - name: Push Tag
        if: steps.version.outputs.TAG_EXISTS == 'false'
        run: |
          git tag ${{ steps.version.outputs.NEXT_VERSION }}
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ steps.version.outputs.NEXT_VERSION }}
