name: Auto Tagging

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Explicitly grant write permission to contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          - name: Determine Next Version
          id: version
          run: |
            # Check for latest git tag
            TAG=$(git tag --sort=-v:refname | head -n 1)

            if [ -z "$TAG" ]; then
              # Fallback to version.txt if no git tags exist
              if [ -f version.txt ]; then
                VERSION=$(cat version.txt)
              else
                VERSION="0.1.0"
              fi
              echo "Using version file: $VERSION"
            else
              VERSION=$TAG
              echo "Using latest tag: $VERSION"
            fi

            # Increment the patch version
            NEXT_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
            echo "Next version: $NEXT_VERSION"

            # Save to GitHub Actions output
            echo "::set-output name=NEXT_VERSION::$NEXT_VERSION"

      - name: Push Tag
        run: |
          git tag ${{ steps.version.outputs.NEXT_VERSION }}
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ steps.version.outputs.NEXT_VERSION }}
