name: Auto Tagging

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine Next Version
        id: version
        run: |
          # Extract the latest tag
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $TAG"

          # Default to v0.1.0 if no tags exist
          if [ -z "$TAG" ]; then
            NEXT_VERSION="v0.1.0"
          else
            # Increment the patch version (vX.Y.Z -> vX.Y.(Z+1))
            NEXT_VERSION=$(echo $TAG | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo "Next version: $NEXT_VERSION"
          echo "::set-output name=NEXT_VERSION::$NEXT_VERSION"

      - name: Create New Tag
        run: |
          git tag ${{ steps.version.outputs.NEXT_VERSION }}
          git push origin ${{ steps.version.outputs.NEXT_VERSION }}

      - name: Deploy or Build (Optional)
        run: echo "Deployment process goes here"
